### Implementation of Python’s Fundamental Libraries

In [1]:
import math 
import numpy as np 
from scipy import linalg

In [2]:
# Math and Statistics Functions 
print("Floor:", math.floor(4.7)) 
print("Ceil:", math.ceil(4.2)) 
print("Square Root:", math.sqrt(16)) 
print("Integer Square Root:", math.isqrt(16)) 
print("GCD:", math.gcd(48, 18))

Floor: 4
Ceil: 5
Square Root: 4.0
Integer Square Root: 4
GCD: 6


In [3]:
# NumPy Array Attributes and Methods 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("Dimensions:", arr.ndim) 
print("Shape:", arr.shape) 
print("Size:", arr.size) 
print("Sum:", np.sum(arr)) 
print("Mean:", np.mean(arr)) 
print("Sorted:", np.sort(arr, axis=1))
print("Sine of elements:", np.sin(arr)) 

Dimensions: 2
Shape: (2, 3)
Size: 6
Sum: 21
Mean: 3.5
Sorted: [[1 2 3]
 [4 5 6]]
Sine of elements: [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [4]:
# Matrix Operations 
matrix = np.array([[4, 7], [2, 6]]) 
print("Determinant:", linalg.det(matrix)) 
eigenvalues, eigenvectors = linalg.eig(matrix) 
print("Eigenvalues:", eigenvalues) 
print("Eigenvectors:\n", eigenvectors)

Determinant: 9.999999999999998
Eigenvalues: [1.12701665+0.j 8.87298335+0.j]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [7]:
# Reshaping 
lst = np.arange(6) 
mat_2D = lst.reshape(2, 3) 
mat_3D = lst.reshape(1, 2, 3) 
print("1d Matrix:\n",lst)
print("2D Matrix:\n", mat_2D) 
print("3D Matrix:\n", mat_3D)

1d Matrix:
 [0 1 2 3 4 5]
2D Matrix:
 [[0 1 2]
 [3 4 5]]
3D Matrix:
 [[[0 1 2]
  [3 4 5]]]
